services:
  web:
    build:
      context: .
    container_name: lead_management_service
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "

  db:
    image: postgres:15
    container_name: lead_management_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: lead_admin
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: lead_management_db

volumes:
  postgres_data:
